# Model Training

### scikit - learn

https://scikit-learn.org/stable/

scikitlearn (sklearn) provides simple and efficient tools for predictive data analysis. It is built on NumPy, SciPy, and matplotlib.

First thing, Import all the libraries

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
pd.set_option('display.max_columns', 50)
 # import linear regression model
from sklearn.linear_model import LinearRegression
# import module for train test split
from sklearn.model_selection import train_test_split

In [5]:
# next load the data
df = pd.read_csv('../data/final.csv')
df.head()

,price,year_sold,property_tax,insurance,beds,baths,sqft,year_built,lot_size,basement,popular,recession,property_age,property_type_Condo
0,295850,2013,234,81,1,1,584,2013,0,0,0,1,0,1
1,216500,2006,169,51,1,1,612,1965,0,0,0,0,41,1
2,279900,2012,216,74,1,1,615,1963,0,0,0,1,49,1
3,379900,2005,265,92,1,1,618,2000,33541,1,0,0,5,0
4,340000,2002,88,30,1,1,634,1992,0,0,0,0,10,1

In [6]:
df.tail()

,price,year_sold,property_tax,insurance,beds,baths,sqft,year_built,lot_size,basement,popular,recession,property_age,property_type_Condo
1855,760000,2008,881,249,5,5,7842,2003,436035,1,0,0,5,0
1856,690000,2015,1553,473,5,6,6501,1956,23086,1,0,0,59,0
1857,600000,1999,942,287,5,6,7064,1995,217800,1,0,0,4,0
1858,759900,2009,803,245,5,6,7500,2006,8886,1,0,0,3,0
1859,735000,2015,1459,444,5,6,7515,1958,10497,1,0,0,57,0

In [7]:
df.shape

(1860, 14)

## Linear Regression Model

In [8]:
# seperate input features in x
x = df.drop('price', axis=1) # axis=1 will drop a column.

# store the target variable in y
y = df['price']

**Train Test Split**
* Training sets are used to fit and tune your models.
* Test sets are put aside as "unseen" data to evaluate your models.
* The `train_test_split()` function splits data into randomized subsets.

## First Train / Test split

In [9]:
# Split the dataset
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, stratify=x.property_type_Condo)

In [10]:
x_train.property_type_Condo.value_counts()

property_type_Condo
0    1208
1     280
Name: count, dtype: int64

In [11]:
x_train.head()

,year_sold,property_tax,insurance,beds,baths,sqft,year_built,lot_size,basement,popular,recession,property_age,property_type_Condo
1231,2013,430,131,4,3,2020,1965,20037,1,0,1,48,0
1440,1995,983,299,4,3,4050,1995,6250,1,0,0,0,0
399,2011,336,102,3,2,972,1964,21780,1,0,1,47,0
1748,1995,1053,321,5,4,3380,1979,23958,1,0,0,16,0
1312,2002,363,103,4,3,2624,2002,5227,1,0,0,0,0

## Size of each Vector

In [12]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((1488, 13), (1488,), (372, 13), (372,))

## Build Linear Regression model on Training set

In [13]:
# train your model
model = LinearRegression()
lrmodel = model.fit(x_train, y_train)

In [14]:
lrmodel.coef_

array([ 8.18004408e+03, -3.95627494e+01,  1.57452471e+03,  5.23460003e+03,
       -6.15043559e+03,  1.21688861e+01,  4.63257966e+03,  1.92903341e-01,
        1.25318019e+04,  4.28349598e-01, -4.69882697e+04,  3.54746442e+03,
       -1.25318019e+04])

In [15]:
lrmodel.intercept_

np.float64(-25494387.845690392)

In [16]:
x_train.head(1)

,year_sold,property_tax,insurance,beds,baths,sqft,year_built,lot_size,basement,popular,recession,property_age,property_type_Condo
1231,2013,430,131,4,3,2020,1965,20037,1,0,1,48,0

## Now Make predictions on Training Set

In [17]:
# make preditions on train set
train_pred = lrmodel.predict(x_train)

In [18]:
train_pred

array([431065.94290971, 564197.74783523, 353082.56592301, ...,
       608267.06947209, 376155.77133392, 508626.49143954])

## Compute the Model Error

In [19]:
# evaluate your model
# we need mean absolute error
from sklearn.metrics import mean_absolute_error

train_mae = mean_absolute_error(train_pred, y_train)
print('Train error is', train_mae)

Train error is 83992.10078465575

## Now Make predictions on Test Set

In [20]:
# make predictions on test set
ypred = lrmodel.predict(x_test)

#evaluate the model
test_mae = mean_absolute_error(ypred, y_test)
print('Test error is', test_mae)

Test error is 87119.33768689432

### Our model is still not good beacuse we need a model with Mean Absolute Error < $70,000

Note - We have not scaled the features and not tuned the model.

## Random Forest Model

In [21]:
# import decision tree model
from sklearn.ensemble import RandomForestRegressor

In [22]:
# create an instance of the model
rf = RandomForestRegressor(n_estimators=200, criterion='absolute_error')

In [23]:
# train the model
rfmodel = rf.fit(x_train,y_train)

In [24]:
# make prediction on train set
ytrain_pred = rfmodel.predict(x_train)

In [25]:
# make predictions on the x_test values
ytest_pred = rfmodel.predict(x_test)

In [26]:
# evaluate the model
test_mae = mean_absolute_error(ytest_pred, y_test)
test_mae

46346.50790994623

In [27]:
# Individual Decision Trees
# tree.plot_tree(rfmodel.estimators_[2], feature_names=dtmodel.feature_names_in_)

## Pickle:

* The pickle module implements a powerful algorithm for serializing and de-serializing a Python object structure.

* The saving of data is called Serialization, and loading the data is called De-serialization.

**Pickle** model provides the following functions:
* **`pickle.dump`** to serialize an object hierarchy, you simply use `dump()`.
* **`pickle.load`** to deserialize a data stream, you call the `loads()` function.

In [ ]:
# # import pickle to save model
# import pickle

# # Save the trained model on the drive
# pickle.dump(dtmodel, open('RE_Model','wb'))

NameError: name 'dtmodel' is not defined

In [ ]:
# # Load the pickled model
# RE_Model = pickle.load(open('RE_Model','rb'))

np.array(xtrain.loc[22])
ytrain[22]

In [ ]:
# # Use the loaded pickled model to make predictions
# RE_Model.predict([[2012, 216, 74, 1 , 1, 618, 2000, 600, 1, 0, 0, 6, 0]])

NameError: name 'RE_Model' is not defined

In [ ]:
x_test.head(1)

In [32]:
import pickle
from pathlib import Path

MODELS_DIR = Path('../models/Real Estate')
MODELS_DIR.mkdir(parents=True, exist_ok=True)

pickle.dump(lrmodel, open(MODELS_DIR / 'Linear_Regression_model.pkl', 'wb'))
pickle.dump(rfmodel, open(MODELS_DIR / 'Random_Forest_model.pkl', 'wb'))