# Model Training

### scikit - learn

https://scikit-learn.org/stable/

scikitlearn (sklearn) provides simple and efficient tools for predictive data analysis. It is built on NumPy, SciPy, and matplotlib.

First thing, Import all the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
pd.set_option('display.max_columns', 50)
 # import linear regression model
from sklearn.linear_model import LinearRegression
# import module for train test split
from sklearn.model_selection import train_test_split

In [2]:
# next load the data
df = pd.read_csv('../data/final.csv')
df.head()

,price,year_sold,property_tax,insurance,beds,baths,sqft,year_built,lot_size,basement,popular,recession,property_age,property_type_Condo
0,295850,2013,234,81,1,1,584,2013,0,0,0,1,0,1
1,216500,2006,169,51,1,1,612,1965,0,0,0,0,41,1
2,279900,2012,216,74,1,1,615,1963,0,0,0,1,49,1
3,379900,2005,265,92,1,1,618,2000,33541,1,0,0,5,0
4,340000,2002,88,30,1,1,634,1992,0,0,0,0,10,1

In [3]:
df.tail()

,price,year_sold,property_tax,insurance,beds,baths,sqft,year_built,lot_size,basement,popular,recession,property_age,property_type_Condo
1855,760000,2008,881,249,5,5,7842,2003,436035,1,0,0,5,0
1856,690000,2015,1553,473,5,6,6501,1956,23086,1,0,0,59,0
1857,600000,1999,942,287,5,6,7064,1995,217800,1,0,0,4,0
1858,759900,2009,803,245,5,6,7500,2006,8886,1,0,0,3,0
1859,735000,2015,1459,444,5,6,7515,1958,10497,1,0,0,57,0

In [4]:
df.shape

(1860, 14)

## Linear Regression Model

In [5]:
# seperate input features in x
x = df.drop('price', axis=1) # axis=1 will drop a column.

# store the target variable in y
y = df['price']

**Train Test Split**
* Training sets are used to fit and tune your models.
* Test sets are put aside as "unseen" data to evaluate your models.
* The `train_test_split()` function splits data into randomized subsets.

## First Train / Test split

In [6]:
# Split the dataset
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, stratify=x.property_type_Condo)

In [7]:
x_train.property_type_Condo.value_counts()

property_type_Condo
0    1208
1     280
Name: count, dtype: int64

In [8]:
x_train.head()

,year_sold,property_tax,insurance,beds,baths,sqft,year_built,lot_size,basement,popular,recession,property_age,property_type_Condo
981,2004,330,115,4,2,1302,1954,10558,1,0,0,50,0
545,2009,368,94,3,2,1637,1988,6969,1,0,0,21,0
39,2012,190,66,1,1,759,1959,0,0,0,1,53,1
1151,2000,389,118,4,3,1249,1977,8894,1,0,0,23,0
135,2009,208,72,2,1,1032,1958,0,0,0,0,51,1

## Size of each Vector

In [9]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((1488, 13), (1488,), (372, 13), (372,))

## Build Linear Regression model on Training set

In [10]:
# train your model
model = LinearRegression()
lrmodel = model.fit(x_train, y_train)

In [11]:
lrmodel.coef_

array([ 7.74457907e+03, -5.02798604e+02,  2.48373999e+03,  6.12452005e+03,
        2.31051139e+03,  3.37571525e+01,  4.31079829e+03,  2.17018912e-01,
        1.29404858e+04,  4.73416598e+03, -4.64757832e+04,  3.43378078e+03,
       -1.29404858e+04])

In [12]:
lrmodel.intercept_

np.float64(-23968861.461520504)

In [13]:
x_train.head(1)

,year_sold,property_tax,insurance,beds,baths,sqft,year_built,lot_size,basement,popular,recession,property_age,property_type_Condo
981,2004,330,115,4,2,1302,1954,10558,1,0,0,50,0

## Now Make predictions on Training Set

In [14]:
# make preditions on train set
train_pred = lrmodel.predict(x_train)

In [15]:
train_pred

array([354273.14211579, 373123.89503841, 283111.40763735, ...,
       362032.78057493, 551592.83783168, 312952.39935274])

## Compute the Model Error

In [16]:
# evaluate your model
# we need mean absolute error
from sklearn.metrics import mean_absolute_error

train_mae = mean_absolute_error(train_pred, y_train)
print('Train error is', train_mae)

Train error is 86984.27117043138

## Now Make predictions on Test Set

In [17]:
# make predictions on test set
ypred = lrmodel.predict(x_test)

#evaluate the model
test_mae = mean_absolute_error(ypred, y_test)
print('Test error is', test_mae)

Test error is 83092.96108248168

### Our model is still not good beacuse we need a model with Mean Absolute Error < $70,000

Note - We have not scaled the features and not tuned the model.

## Random Forest Model

In [18]:
# import decision tree model
from sklearn.ensemble import RandomForestRegressor

In [19]:
# create an instance of the model
rf = RandomForestRegressor(n_estimators=200, criterion='absolute_error')

In [20]:
# train the model
rfmodel = rf.fit(x_train,y_train)

In [21]:
# make prediction on train set
ytrain_pred = rfmodel.predict(x_train)

In [22]:
# make predictions on the x_test values
ytest_pred = rfmodel.predict(x_test)

In [23]:
# evaluate the model
test_mae = mean_absolute_error(ytest_pred, y_test)
test_mae

40844.71906586021

In [24]:
# Individual Decision Trees
# tree.plot_tree(rfmodel.estimators_[2], feature_names=dtmodel.feature_names_in_)

## Pickle:

* The pickle module implements a powerful algorithm for serializing and de-serializing a Python object structure.

* The saving of data is called Serialization, and loading the data is called De-serialization.

**Pickle** model provides the following functions:
* **`pickle.dump`** to serialize an object hierarchy, you simply use `dump()`.
* **`pickle.load`** to deserialize a data stream, you call the `loads()` function.

In [25]:
# # import pickle to save model
# import pickle

# # Save the trained model on the drive
# pickle.dump(dtmodel, open('RE_Model','wb'))

In [26]:
# # Load the pickled model
# RE_Model = pickle.load(open('RE_Model','rb'))

np.array(xtrain.loc[22])
ytrain[22]

In [27]:
# # Use the loaded pickled model to make predictions
# RE_Model.predict([[2012, 216, 74, 1 , 1, 618, 2000, 600, 1, 0, 0, 6, 0]])

In [28]:
x_test.head(1)

,year_sold,property_tax,insurance,beds,baths,sqft,year_built,lot_size,basement,popular,recession,property_age,property_type_Condo
1857,1999,942,287,5,6,7064,1995,217800,1,0,0,4,0

In [29]:
# import pickle
# from pathlib import Path

# MODELS_DIR = Path('../models/Real Estate')
# MODELS_DIR.mkdir(parents=True, exist_ok=True)

# pickle.dump(lrmodel, open(MODELS_DIR / 'Linear_Regression_model.pkl', 'wb'))
# pickle.dump(rfmodel, open(MODELS_DIR / 'Random_Forest_model.pkl', 'wb'))

In [32]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import numpy as np
import joblib
from pathlib import Path


MODELS_DIR = Path('../models/Real Estate')
MODELS_DIR.mkdir(parents=True, exist_ok=True)

# Calculate metrics
lr_model = joblib.load(MODELS_DIR / 'Linear_Regression_model.pkl')
y_pred_lr = lr_model.predict(x_test)
lr_metrics = {
    'r2_score': r2_score(y_test, y_pred_lr),
    'rmse': np.sqrt(mean_squared_error(y_test, y_pred_lr)),
    'mae': mean_absolute_error(y_test, y_pred_lr),
    'mse': mean_squared_error(y_test, y_pred_lr)
}

# Calculate F-statistic (for Linear Regression)
from scipy import stats
n = len(y_test)
p = x_test.shape[1]
r2 = lr_metrics['r2_score']
f_statistic = (r2 / p) / ((1 - r2) / (n - p - 1))
p_value = 1 - stats.f.cdf(f_statistic, p, n - p - 1)

lr_metrics['f_statistic'] = f_statistic
lr_metrics['p_value'] = p_value

# Save metrics
joblib.dump(lr_metrics, '../models/Real Estate/Linear_Regression_metrics.pkl')

# After training Random Forest model
y_pred_rf = rfmodel.predict(x_test)
rf_metrics = {
    'r2_score': r2_score(y_test, y_pred_rf),
    'rmse': np.sqrt(mean_squared_error(y_test, y_pred_rf)),
    'mae': mean_absolute_error(y_test, y_pred_rf),
    'mse': mean_squared_error(y_test, y_pred_rf)
}

# Add OOB score if available
if hasattr(rfmodel, 'oob_score_'):
    rf_metrics['oob_score'] = rfmodel.oob_score_

# Save metrics
joblib.dump(rf_metrics, '../models/Real Estate/Random_Forest_metrics.pkl')

['../models/Real Estate/Random_Forest_metrics.pkl']